name: Test

on:
  push:
  pull_request:

jobs:
  build-windows:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, windows-2019, ubuntu-latest]
        python-version: [3.7.9, 3.10.4]
        
    env:
      JOB_TYPE: BUILD
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install -r src/Requirements.txt
          python -m pip install prospector

      - name: Control code structure
        run: |
          prospector
          
      - name: Generate anonymized tests
        run: |
          cd src
          python dicomanonymize/scripts/main.py -i test/Named -o test/test

      - name: Run tests
        run: |
          cd src
          python test/test.py