name: Test

on:
  push:
  pull_request:

jobs:
  build-windows:
    name: Build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-2022, ubuntu-latest]
        python-version: [3.6.8, 3.7.9, 3.10.4]
        
    env:
      JOB_TYPE: BUILD
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
          architecture: x64
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          # python -m pip install -r Requirements.txt

      - name: Install package
        run: |
          python -m pip install .

      - name: Control code structure
        run: |
          python -m pip install .[test]
          prospector --profile extras/profile.yaml
          
      - name: Generate anonymized tests
        run: |
          cd src
          dicomanonymize -i test/Named -o test/test

      - name: Run tests
        run: |
          cd src/test
          pytest test.py